# docker-compose -f docker-compose.prod.yml build
# docker-compose -f docker-compose.prod.yml up -d
# docker-compose -f docker-compose.prod.yml down

version: '3.3'

services:

  mongodb:
    image: mongo
    container_name: mongodb-instance-microservices    
    ports: 
      - "27017:27017"
    networks:
      - microservices-network

  client:
    container_name: client-instance-microservices
    image: client-microservices
    build:
      context: ./client
      dockerfile: prod.dockerfile
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
       - api
    networks:
      - microservices-network

  api:
    container_name: api-instance-microservices
    image: api-microservices
    build:
      context: ./server
      dockerfile: server.dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3333"
    depends_on:
       - mongodb
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge